cassandra:
  contact-points: 127.0.0.1
  port: 9042
  schema-action: create_if_not_exists
  local-datacenter: datacenter1
  keyspace-name: test2
  replicationFactor: 2

spring:
  cassandra:
    schema-action: create_if_not_exists